### ISSUE TITLE
create vidi instance using <video> element tag

### ISSUE THREAD

**Issue by abumami** [wix/vidi#14]
Instead of doing this to create a vidi instance:
var videoElement = document.getElementById('my-video-element');
var vidi = new Vidi(videoElement);

Couldn't the tag be used directly:
var vidi = new Vidi('my-video-element');

**Comment by AviVahl** [comment]
Providing the id feels implicit. Thats a `string`, alright... Is it a class on that element? Why the id? some developers don't like using ids in their html. Besides, a node can be found in various ways. In React, for example, I use a ref function, where React provides me with a reference to the node. See demo code:
https://github.com/wix/vidi/blob/master/demo/src/App.js#L41

I want the connection between a `vidi` instance and a single video to be explicit. The developer should be the one declaring it and managing the instance.
Auto-scanning for `<video>` elements is way too intrusive and feels like a bad practice. It might be easier in some cases, yet destructive in others. 
It also beats the purpose of using vidi for multiple possible sources, as the `src` attribute of a `<video>` element cannot contain multiple sources on its own.

Closing as `wontfix`.
